"""Boards for Tanka: tables the assistant fills and the user reads on the page, grouped and counted.

- A **view** (`<workspace>/.claude/views/<name>.json`, written by the user or `/new-view`, never by the
  assistant) declares the fields of a row, which of them identify it (the key), how rows are grouped
  on the page, and the buttons a row offers. At most MAX_FIELDS fields, because each one becomes a
  typed param of the view's own tool.
- `build` turns each view into a tool, `boards_record_<view>`, with one param per field: the harness
  checks the types, the choices and the bounds before the tool runs. `boards_rows` reads any view.
- Rows live in HOME/<workspace>/<view>.json, outside every workspace, so the assistant reaches them
  only through its tools.

A row's button never acts: it writes a message in the chat's box for the user to read and send.

Standard library only.
"""
from __future__ import annotations

import contextlib
import fcntl
import hashlib
import json
import os
import re
import sys
import unicodedata
from datetime import datetime
from pathlib import Path

MODULE = Path(__file__).resolve().parent
REPO = MODULE.parents[1]
sys.path.insert(0, str(REPO / "plugin" / "scripts"))
import tanka_kit as kit  # noqa: E402
from tanka_kit import ToolError, clip, now, read_json, run, safe_id, scrub, write_json  # noqa: E402,F401

HOME = Path(os.environ.get("TANKA_BOARDS_HOME", kit.SHARED / "boards"))
VIEW_RE = re.compile(r"[a-z][a-z0-9_]{1,23}")
FIELD_RE = re.compile(r"[a-z][a-z0-9_]{0,23}")
TYPES = ("text", "number", "choice", "date")
TONES = ("info", "warn", "good", "accent", "bad", "dev", "neutral")  # the page's colours for a choice's values
MAX_FIELDS, MAX_KEY, MAX_VIEWS, MAX_ACTIONS = 6, 4, 5, 4
SHORT_CHARS, LONG_CHARS = 200, 2000
MAX_ROWS = 2000
SHOW_ROWS = 60               # rows one boards_rows call lists; the rest are counted
EXAMPLE_CHARS = 120          # a long text in the tool's example, cut to this
TOOL_PREFIX = "boards_record_"
GENERATED = "generated by `tanka boards build`"
PLACEHOLDER_RE = re.compile(r"\{([a-z][a-z0-9_]*)\}")


# ---------------------------------------------------------------- views

def views_dir(ws: Path) -> Path:
    return ws / ".claude" / "views"


def installed(ws: Path) -> bool:
    """Whether the boards skill (boards_rows and the boards_record_<view> tools) is in the workspace."""
    return (ws / ".claude" / "skills" / "boards").is_dir()


def has_views(ws: Path) -> bool:
    """Whether the workspace declares a board: enough for the page, even without the skill."""
    return views_dir(ws).is_dir() and any(views_dir(ws).glob("*.json"))


def load_views(ws: Path) -> dict[str, dict]:
    """{name: spec} for every view file; a file that is not valid JSON is skipped (check names it)."""
    out = {}
    for f in sorted(views_dir(ws).glob("*.json")) if views_dir(ws).is_dir() else []:
        try:
            spec = json.loads(f.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(spec, dict):
            out[f.stem] = spec
    return out


def fields_of(spec: dict) -> dict[str, dict]:
    f = spec.get("fields")
    return f if isinstance(f, dict) else {}


def view_problems(name: str, spec: dict) -> list[str]:
    """What keeps a view from becoming a tool and a board; empty when it is ready."""
    p = []
    if not VIEW_RE.fullmatch(name):
        p.append("the file name must be 2-24 lowercase letters, digits or _, starting with a letter")
    title = spec.get("title")
    if not isinstance(title, str) or not 1 <= len(title) <= 40:
        p.append("title must be 1-40 characters")
    desc = spec.get("description")
    if not isinstance(desc, str) or not 20 <= len(desc) <= 300:
        p.append("description must be 20-300 characters: what one row is, in the user's words")
    fields = fields_of(spec)
    if not 1 <= len(fields) <= MAX_FIELDS:
        p.append(f"fields must have 1-{MAX_FIELDS} entries: each becomes one param of the view's tool")
    for fname, f in fields.items():
        where = f"field '{fname}'"
        if not FIELD_RE.fullmatch(fname):
            p.append(f"{where}: name must be snake_case, at most 24 characters")
        if not isinstance(f, dict):
            p.append(f"{where}: must be an object")
            continue
        if f.get("type") not in TYPES:
            p.append(f"{where}: type must be one of {', '.join(TYPES)}")
        label = f.get("label")
        if not isinstance(label, str) or not 1 <= len(label) <= 30:
            p.append(f"{where}: label must be 1-30 characters")
        hint = f.get("hint", "")
        if not isinstance(hint, str) or len(hint) > 160:
            p.append(f"{where}: hint must be at most 160 characters")
        if f.get("type") == "choice":
            ch = f.get("choices")
            if not isinstance(ch, list) or not 2 <= len(ch) <= 12 or len({str(c).lower() for c in ch}) != len(ch) \
                    or not all(isinstance(c, str) and 1 <= len(c) <= 30 for c in ch):
                p.append(f"{where}: choices must list 2-12 distinct values of 1-30 characters")
        if f.get("type") == "number":
            lo, hi = f.get("min"), f.get("max")
            if any(v is not None and not isinstance(v, (int, float)) for v in (lo, hi)) or \
                    (lo is not None and hi is not None and lo >= hi):
                p.append(f"{where}: min and max must be numbers with min below max")
        tones = f.get("tones")
        if tones is not None and (f.get("type") != "choice" or not isinstance(tones, dict)
                                  or any(k not in (f.get("choices") or []) or v not in TONES for k, v in tones.items())):
            p.append(f"{where}: tones maps some of its choices to one of {', '.join(TONES)}")
        if "long" in f and f.get("type") != "text":
            p.append(f"{where}: long applies to text only")
        if "editable" in f and f.get("type") != "choice":
            p.append(f"{where}: editable applies to choice fields only (the page offers a select)")
    key = spec.get("key")
    if not isinstance(key, list) or not 1 <= len(key) <= MAX_KEY or len(set(key)) != len(key):
        p.append(f"key must list 1-{MAX_KEY} distinct fields: the ones that say which row it is")
    else:
        for k in key:
            if k not in fields:
                p.append(f"key names '{k}', which is not a field")
            elif fields[k].get("type") == "text" and fields[k].get("long"):
                p.append(f"key field '{k}' cannot be long text")
    group = spec.get("group_by")
    if group is not None and group not in fields:
        p.append(f"group_by names '{group}', which is not a field")
    cols = spec.get("columns")
    if cols is not None and (not isinstance(cols, list) or any(c not in fields for c in cols)):
        p.append("columns must list fields only")
    actions = spec.get("actions", [])
    if not isinstance(actions, list) or len(actions) > MAX_ACTIONS:
        p.append(f"actions must list at most {MAX_ACTIONS} buttons")
        actions = []
    for i, a in enumerate(actions, 1):
        where = f"action {i}"
        if not isinstance(a, dict):
            p.append(f"{where}: must be an object")
            continue
        if not isinstance(a.get("label"), str) or not 1 <= len(a["label"]) <= 24:
            p.append(f"{where}: label must be 1-24 characters")
        says = a.get("says")
        if not isinstance(says, str) or not 10 <= len(says) <= 300:
            p.append(f"{where}: says must be 10-300 characters, the message it writes for the user to send")
        else:
            for ph in PLACEHOLDER_RE.findall(says):
                if ph not in fields:
                    p.append(f"{where}: says names {{{ph}}}, which is not a field")
        when = a.get("when", {})
        if not isinstance(when, dict):
            p.append(f"{where}: when must map choice fields to the values that show the button")
        else:
            for fname, vals in when.items():
                f = fields.get(fname, {})
                allowed = [str(c).lower() for c in f.get("choices", [])] if f.get("type") == "choice" else None
                vals = vals if isinstance(vals, list) else [vals]
                if allowed is None or any(str(v).lower() not in allowed for v in vals):
                    p.append(f"{where}: when must name a choice field and some of its choices")
    example = spec.get("example")
    if not isinstance(example, dict):
        p.append("example must be one complete row: it shows the assistant what a call looks like")
    elif not p:
        try:
            normalize(name, spec, example)
        except ToolError as e:
            p.append(f"example: {e}")
    return p


def check(ws: Path) -> tuple[list[str], list[str]]:
    """(problems, warnings) for a workspace's views."""
    problems, warnings = [], []
    files = sorted(views_dir(ws).glob("*.json")) if views_dir(ws).is_dir() else []
    if len(files) > MAX_VIEWS:
        problems.append(f"{len(files)} views: at most {MAX_VIEWS}, one tool each")
    for f in files:
        try:
            spec = json.loads(f.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            problems.append(f"{f.name}: not valid JSON ({e})")
            continue
        if not isinstance(spec, dict):
            problems.append(f"{f.name}: must be a JSON object")
            continue
        problems += [f"{f.stem}: {x}" for x in view_problems(f.stem, spec)]
    if not files:
        warnings.append(f"no views yet in {views_dir(ws)}: build one with /new-view in `tanka dev <workspace>`")
    return problems, warnings


# ---------------------------------------------------------------- one row

def norm(s) -> str:
    return re.sub(r"\s+", " ", str(s or "")).strip()


def fold(s) -> str:
    """How two spellings of one key compare: no case, no accents, single spaces ("Ana  Perez" is "Ana Pérez")."""
    decomposed = unicodedata.normalize("NFKD", norm(s).lower())
    return "".join(ch for ch in decomposed if not unicodedata.combining(ch))


def value_of(fname: str, f: dict, raw) -> object:
    """A field's value as stored, or a ToolError that says what this field takes."""
    t = f.get("type")
    if t == "number":
        try:
            v = float(raw)
        except (TypeError, ValueError):
            raise ToolError(f"{fname} is a number (e.g. {f.get('min', 1)}), not '{clip(raw, 40)}'.") from None
        if f.get("min") is not None and v < f["min"] or f.get("max") is not None and v > f["max"]:
            raise ToolError(f"{fname} goes from {f.get('min', '…')} to {f.get('max', '…')}; {v:g} is outside.")
        return int(v) if v.is_integer() else round(v, 4)
    text = scrub(raw).strip() if f.get("long") else norm(scrub(raw))
    if not text:
        raise ToolError(f"{fname} cannot be empty; leave it out to keep what the row has.")
    if t == "choice":
        match = [c for c in f["choices"] if c.lower() == text.lower()]
        if not match:
            raise ToolError(f"{fname} is one of: {', '.join(f['choices'])} (got '{clip(text, 40)}').")
        return match[0]
    if t == "date":
        try:
            datetime.strptime(text, "%Y-%m-%d")
        except ValueError:
            raise ToolError(f"{fname} is a date like 2026-10-01 (got '{clip(text, 40)}').") from None
        return text
    limit = LONG_CHARS if f.get("long") else SHORT_CHARS
    if len(text) > limit:
        raise ToolError(f"{fname} is at most {limit} characters; shorten it.")
    return text


def normalize(view: str, spec: dict, args: dict) -> dict:
    """The fields of one call, validated: every key field, and only the view's fields."""
    fields = fields_of(spec)
    unknown = [k for k in args if k not in fields]
    if unknown:
        raise ToolError(f"{view} has no field {', '.join(unknown)}; its fields are {', '.join(fields)}.")
    missing = [k for k in spec["key"] if norm(args.get(k)) == ""]
    if missing:
        raise ToolError(f"Say which row: {', '.join(missing)} {'is' if len(missing) == 1 else 'are'} needed "
                        f"({' + '.join(spec['key'])} name a row). If you do not know, ask.")
    return {k: value_of(k, fields[k], v) for k, v in args.items() if v is not None and norm(v) != ""}


def row_id(spec: dict, values: dict) -> str:
    key = "\x1f".join(fold(values[k]) for k in spec["key"])
    return "r" + hashlib.sha1(key.encode()).hexdigest()[:10]


def rows_file(scope: str, view: str) -> Path:
    return HOME / safe_id(scope) / f"{safe_id(view)}.json"


@contextlib.contextmanager
def row_store(scope: str, view: str, write: bool = False):
    """A view's rows under an exclusive lock: the tool, the page and the CLI all write here."""
    f = rows_file(scope, view)
    f.parent.mkdir(parents=True, exist_ok=True)
    with open(f.with_suffix(".lock"), "a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        data = read_json(f, {"rows": []})
        yield data["rows"]
        if write:
            write_json(f, data)


def view_spec(scope: str, view: str) -> dict:
    ws = kit.ws_dir(scope)
    spec = load_views(ws).get(view)
    if spec is None:
        names = ", ".join(load_views(ws)) or "none yet"
        raise ToolError(f"No view named {view} (views: {names}).")
    problems = view_problems(view, spec)
    if problems:
        raise ToolError(f"The view {view} is broken ({problems[0]}). Tell the user; it is fixed with /new-view.")
    return spec


def record(scope: str, view: str, args: dict, by: str = "assistant") -> tuple[dict, list[str]]:
    """Add the row, or update the fields given on the row with the same key. Returns (row, what changed)."""
    spec = view_spec(scope, view)
    values = normalize(view, spec, args)
    rid, t = row_id(spec, values), round(now(), 3)
    with row_store(scope, view, write=True) as rows:
        row = next((r for r in rows if r["id"] == rid), None)
        if row is None:
            if len(rows) >= MAX_ROWS:
                raise ToolError(f"{view} holds {MAX_ROWS} rows, the limit. Tell the user; old rows are archived on the page.")
            row = {"id": rid, "fields": {}, "t": t, "by": by}
            rows.append(row)
            changed = list(values)
        else:
            # The row keeps the spelling its key was first written with.
            values = {k: v for k, v in values.items() if k not in spec["key"]}
            changed = [k for k, v in values.items() if row["fields"].get(k) != v]
        row["fields"].update(values)
        if changed:
            row["updated"], row["updated_by"], row["changed"] = t, by, changed
        return dict(row), changed


def try_record(scope: str, view: str, args: dict, by: str = "assistant") -> bool:
    """`record` for another tool that notes its outcome on a board: it never raises, so the tool's own
    work never fails because of the board. Returns whether the row was written; on failure says why on
    stderr, which the harness ignores when the tool exits 0. Needs only the view, not the boards skill."""
    try:
        record(scope, view, {k: v for k, v in args.items() if v is not None}, by=by)
        return True
    except Exception as e:  # noqa: BLE001 - a board is a side note: nothing about it may stop the caller
        print(f"boards: {view} row not recorded: {e}", file=sys.stderr)
        return False


def set_field(scope: str, view: str, rid: str, field: str, value: str) -> dict:
    """The page's select on an editable choice field."""
    spec = view_spec(scope, view)
    f = fields_of(spec).get(field)
    if not f or f.get("type") != "choice" or not f.get("editable"):
        raise ToolError(f"{field} is not a field the page can change in {view}.")
    with row_store(scope, view, write=True) as rows:
        row = next((r for r in rows if r["id"] == rid), None)
        if row is None:
            raise ToolError(f"No row {rid} in {view}.")
        v = value_of(field, f, value)
        if row["fields"].get(field) != v:
            row["fields"][field] = v
            row["updated"], row["updated_by"], row["changed"] = round(now(), 3), "user", [field]
        return dict(row)


def archive(scope: str, view: str, rid: str) -> dict:
    with row_store(scope, view, write=True) as rows:
        row = next((r for r in rows if r["id"] == rid), None)
        if row is None:
            raise ToolError(f"No row {rid} in {view}.")
        row["archived"] = round(now(), 3)
        return dict(row)


def live_rows(scope: str, view: str) -> list[dict]:
    with row_store(scope, view) as rows:
        return [r for r in rows if not r.get("archived")]


# ---------------------------------------------------------------- the tools

def label_of(spec: dict, row: dict) -> str:
    return " · ".join(str(row["fields"].get(k, "")) for k in spec["key"])


def rows_tool(scope: str, view: str | None, match: str | None) -> None:
    """boards_rows: the views, or one view's rows."""
    ws = kit.ws_dir(scope)
    if not view:
        views = load_views(ws)
        if not views:
            print("No boards yet. The user declares one with /new-view in tanka dev; you cannot make one.")
            return
        for name, spec in views.items():
            if view_problems(name, spec):
                print(f"{name}: broken, see `tanka boards check`. Tell the user.")
                continue
            fields = fields_of(spec)
            desc = "; ".join(f"{k} ({describe_field(f)})" for k, f in fields.items())
            print(f"{name}: {spec['title']}. {spec['description']} {len(live_rows(scope, name))} row(s). "
                  f"Key: {' + '.join(spec['key'])}. Fields: {desc}. "
                  + (f"Record with {TOOL_PREFIX}{name}." if installed(ws) else "Filled by the workspace's own tools."))
        return
    spec = view_spec(scope, view)
    rows = live_rows(scope, view)
    if match:
        m = fold(match)
        rows = [r for r in rows if any(m in fold(r["fields"].get(k)) for k in spec["key"])]
    group = spec.get("group_by")
    rows.sort(key=lambda r: [norm(r["fields"].get(k)).lower() for k in ([group] if group else []) + spec["key"]])
    print(f"{spec['title']}: {len(rows)} row(s)" + (f" matching '{clip(match, 40)}'" if match else "") + ".")
    for r in rows[:SHOW_ROWS]:
        rest = [f"{k}={clip(v, 150)}" for k, v in r["fields"].items() if k not in spec["key"]]
        print(f"{label_of(spec, r)} | " + (" | ".join(rest) or "(nothing else yet)"))
    if len(rows) > SHOW_ROWS:
        print(f"…and {len(rows) - SHOW_ROWS} more: pass match (a course, a name) to narrow it.")


def record_tool(scope: str, view: str, args: dict) -> None:
    row, changed = record(scope, view, args)
    spec = view_spec(scope, view)
    rest = [k for k in changed if k not in spec["key"]]
    if row.get("t") == row.get("updated"):
        what = "new row" + (f" with {', '.join(rest)}" if rest else "")
    else:
        what = f"updated {', '.join(rest)}" if rest else "nothing changed (it already had those values)"
    print(f"{spec['title']} · {label_of(spec, row)}: {what}. It shows on the user's page now. Do not call it again for the same values.")


def describe_field(f: dict) -> str:
    t = f.get("type")
    if t == "choice":
        return "one of " + ", ".join(f["choices"])
    if t == "number":
        lo, hi = f.get("min"), f.get("max")
        return "a number" + (f" from {lo:g} to {hi:g}" if lo is not None and hi is not None else "")
    if t == "date":
        return "a date YYYY-MM-DD"
    return "text" + (", several lines" if f.get("long") else "")


# ---------------------------------------------------------------- build: one tool per view

def tool_manifest(name: str, spec: dict) -> dict:
    fields = fields_of(spec)
    key = spec["key"]
    params = {}
    for k, f in fields.items():
        hint = f.get("hint") or f["label"]
        eg = spec["example"].get(k)
        about = describe_field(f) + (f", e.g. {clip(eg, 60)}" if eg is not None and not f.get("long") else "")
        p = {"type": "number" if f["type"] == "number" else "string", "description": clip(f"{hint} ({about})", 250)}
        if len(p["description"]) < 10:
            p["description"] = clip(f"{f['label']}: {describe_field(f)}", 250)
        if k in key:
            p["required"] = True
        if f["type"] == "choice":
            p["enum"] = list(f["choices"])
        elif f["type"] == "number":
            if f.get("min") is not None:
                p["minimum"] = f["min"]
            if f.get("max") is not None:
                p["maximum"] = f["max"]
        elif f["type"] == "date":
            p["pattern"] = r"^\d{4}-\d{2}-\d{2}$"
        elif not f.get("long"):
            p["pattern"] = r"^[^\n]{1,%d}$" % SHORT_CHARS
        params[k] = p
    others = [k for k in fields if k not in key]
    # The examples only need to be valid: a long text is cut, or they would crowd out the description.
    example = {k: (clip(v, EXAMPLE_CHARS) if fields[k].get("long") else v) for k, v in spec["example"].items() if k in fields}
    desc = (f"Records one row of the user's {spec['title']} board: {spec['description'].rstrip('.')}. "
            f"{' + '.join(key)} say which row it is; the same {' + '.join(key)} again updates that row, "
            f"only the fields you pass" + (f" ({', '.join(others)})" if others else "") + ", so leave out what you do not know. "
            "Use it when the user asks you to record or change something on that board, or a task you are doing produces it. "
            "It shows on the user's page at once. It cannot delete rows. Returns what changed.")
    return {"name": f"{TOOL_PREFIX}{name}", "effect": "draft", "description": desc, "params": params,
            "examples": [example, {k: example[k] for k in key if k in example}] if others else [example],
            "timeout_sec": 20, "run": ["python3", f"{TOOL_PREFIX}{name}.py"]}


def tool_script(name: str, scope: str) -> str:
    return f'''#!/usr/bin/env python3
"""{TOOL_PREFIX}{name}: {GENERATED} from .claude/views/{name}.json. Do not edit; edit the view and build again."""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(os.environ["TANKA_PLUGIN_DIR"]).parent / "modules" / "boards"))
import boards as b  # noqa: E402

SCOPE = "{scope}"
VIEW = "{name}"

b.run(lambda args: b.record_tool(SCOPE, VIEW, args))
'''


SKILL_VIEWS_MARK = "<!-- views: written by tanka boards build -->"


def build(ws: Path, scope: str) -> list[str]:
    """Write one tool per valid view, drop the tools of views that are gone, and list them in SKILL.md.
    Returns what it did, one line each; raises ToolError when the views do not pass check."""
    problems, _ = check(ws)
    if problems:
        raise ToolError("the views do not pass check:\n  " + "\n  ".join(problems))
    sys.path.insert(0, str(REPO / "plugin" / "scripts"))
    import tanka_tools as tt
    tools = ws / ".claude" / "skills" / "boards" / "tools"
    if not tools.is_dir():
        raise ToolError(f"build makes one boards_record_<view> tool per view, and those need the boards skill: "
                        f"tanka install boards {scope}. Without it the page still shows the views, filled by tools "
                        "that call boards.record (README: A board without tools).")
    views = load_views(ws)
    before, _ = tt.scan(ws)
    mine = {f.stem for f in tools.glob(f"{TOOL_PREFIX}*.json")}
    adds = len([v for v in views if f"{TOOL_PREFIX}{v}" not in mine])
    if len(before) + adds > tt.tools_max(ws):
        raise ToolError(f"{ws.name} has {len(before)} tools and the views add {adds}: over the {tt.tools_max(ws)}-tool "
                        "limit. Merge or drop tools first (docs/tool-rules.md).")
    # Every tool is checked as the harness will load it before anything is written: a view that passes
    # check but makes a tool the harness refuses would leave a board the assistant cannot fill.
    made = {name: tool_manifest(name, spec) for name, spec in views.items()}
    refused = [f"{name}: {e}" for name, m in made.items() for e in tt.validate_manifest(m, "boards", m["name"], tt.limits(ws))]
    if refused:
        raise ToolError("the harness would refuse these tools; shorten the view's description or hints:\n  "
                        + "\n  ".join(refused))
    done = []
    for name, spec in views.items():
        stem = f"{TOOL_PREFIX}{name}"
        manifest = json.dumps(made[name], indent=2, ensure_ascii=False) + "\n"
        old = (tools / f"{stem}.json").read_text(encoding="utf-8") if (tools / f"{stem}.json").is_file() else None
        (tools / f"{stem}.json").write_text(manifest, encoding="utf-8")
        (tools / f"{stem}.py").write_text(tool_script(name, scope), encoding="utf-8")
        if old != manifest:
            done.append(f"{'updated' if old else 'made'} {stem}")
    for stem in sorted(mine - {f"{TOOL_PREFIX}{v}" for v in views}):
        script = tools / f"{stem}.py"
        if script.is_file() and GENERATED not in script.read_text(encoding="utf-8"):
            continue  # not ours: leave it
        (tools / f"{stem}.json").unlink(missing_ok=True)
        script.unlink(missing_ok=True)
        done.append(f"removed {stem} (its view is gone)")
    skill = tools.parent / "SKILL.md"
    text = skill.read_text(encoding="utf-8")
    head = text.split(SKILL_VIEWS_MARK)[0].rstrip() + "\n\n" + SKILL_VIEWS_MARK + "\n"
    lines = ["", "| Board | What one row is | Record with |", "| --- | --- | --- |"]
    lines += [f"| {spec['title']} | {spec['description']} | `{TOOL_PREFIX}{name}` |" for name, spec in views.items()]
    skill.write_text(head + ("\n".join(lines) if views else "\nNo boards yet.") + "\n", encoding="utf-8")
    return done
